name: ava_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=2.18.6 <3.0.0"

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.2
    google_fonts:
    socket_io_client: ^2.0.1
    flutter_iconpicker: ^3.2.2
    qr_code_scanner: ^1.0.1
    flutter_slidable: ^2.0.0
    hive: ^2.2.3
    hive_flutter: ^1.1.0
    flutter_colorpicker: ^1.0.3

dev_dependencies:
    flutter_launcher_icons: ^0.11.0
    flutter_test:
        sdk: flutter
    hive_generator:
    build_runner:

    flutter_lints: ^2.0.0

flutter_icons:
    android: true
    ios: true
    macos:
        generate: true
        image_path: "assets/app_icon.png"
    image_path: "assets/app_icon.png"

flutter:
    uses-material-design: true

    assets:
        - assets/images/
